name: Build Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t stefanneuhaus/dependencycheck-central-mysql:latest .

      - name: Login and push to DockerHub
        env:
          DH_PWD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          echo $DH_PWD | docker login -u stefanneuhaus --password-stdin
          docker push stefanneuhaus/dependencycheck-central-mysql:latest
