name: Build Docker Image

on:
  push:
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker image
        uses: actions/checkout@v2
        run: docker build -t dependencycheck-central-mysql:$(date +%s) .
